# These are supported funding model platforms

github: n3c4s
# ko_fi: # Ko-fi username
# open_collective: # Open Collective username
# patreon: # Patreon username
# tidelift: # Tidelift username
# community_bridge: # Community Bridge username
# liberapay: # LiberaPay username
# issuehunt: # IssueHunt username
# otechie: # Otechie username
# custom: # Custom funding URL 